name: release

on:
  push:
    branches: [main]

concurrency: production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Get next release version (dry run)
        id: taggerDryRun
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DRY_RUN: true
      - name: echo new tag
        run: |
          echo "The next tag version will be: ${{ steps.taggerDryRun.outputs.new_tag }}"
      - name: echo tag
        run: |
          echo "The current tag is: ${{ steps.taggerDryRun.outputs.tag }}"
      - name: Build C-Shared Libraries
        run: |
          sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu
          GOOS=linux GOARCH=amd64 go build -buildmode=c-shared -o lib-goastgen_linux_amd64.so
          GOOS=linux GOARCH=arm64 go build -buildmode=c-shared -o lib-goastgen_linux_arm64.so
      - name: Rename
        run: |
          mv lib-goastgen_linux_amd64.so lib-goastgen_linux.so
          mv lib-goastgen_linux_arm64.so lib-goastgen_linux_arm.so
      - name: Set next release version
        id: taggerFinal
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.taggerDryRun.outputs.new_tag }}
          files: |
            lib-goastgen_linux.so
            lib-goastgen_linux_arm.so
            